export const experiences = [
  {
    id: "1",
    role: "Gymnasiale Matur",
    roleEn: "High School Diploma",
    company: "Liechtensteinisches Gymnasium in Vaduz",
    companyEn: "Liechtenstein Gymnasium in Vaduz",
    period: "2015 - 2021",
    periodEn: "2015 - 2021",
    description: "Schwerpunkt Wirtschaft.",
    descriptionEn: "Focus on Economics.",
    details: "Betriebswirtschaft und Volkswirtschaft waren mein Schwerpunkt. Aber abseits der Zahlen war das Gymnasium für mich vor allem die Zeit, in der ich gelernt habe, unabhängig zu sein und Verantwortung für mich selbst zu übernehmen.",
    detailsEn: "Business administration and economics were my focus. But beyond the numbers, high school was the time when I learned to be independent and take responsibility for myself.",
  },
  {
    id: "2",
    role: "Praktikum Service Desk",
    roleEn: "Service Desk Internship",
    company: "Dr. Risch (Labor Risch)",
    companyEn: "Dr. Risch (Labor Risch)",
    period: "2021 (2 Monate)",
    periodEn: "2021 (2 months)",
    description: "Einsatz als Service Desk Mitarbeiter.",
    descriptionEn: "Worked as Service Desk staff.",
    details: "Unterstützung im IT-Support und Bearbeitung von Anfragen im Service Desk. Erste praktische Erfahrungen im professionellen IT-Umfeld.",
    detailsEn: "Supported IT operations and handled service desk requests. First practical experience in a professional IT environment."
  },
  {
    id: "3",
    role: "BSc Informatik",
    roleEn: "BSc Computer Science",
    company: "Ostschweizer Fachhochschule",
    companyEn: "Eastern Switzerland University of Applied Sciences",
    period: "2022 - 2024",
    periodEn: "2022 - 2024",
    description: "Grundlagen der Informatik. (Ohne Abschluss)",
    descriptionEn: "Computer Science Fundamentals. (No degree)",
    details: "Vertiefung in Software Engineering, Datenbanken und Human-Computer Interaction. Wechsel des Fokus in Richtung Design und UX, um kreativere Lösungen zu erarbeiten.",
    detailsEn: "Specialized in Software Engineering, Databases and Human-Computer Interaction. Shifted focus towards Design and UX to create more creative solutions."
  },
  {
    id: "4",
    role: "Service Desk Mitarbeiter",
    roleEn: "Service Desk Employee",
    company: "Liechtensteinische Landesverwaltung",
    companyEn: "Liechtenstein National Administration",
    period: "2022 - 2023",
    periodEn: "2022 - 2023",
    description: "Einsatz als Service Desk Mitarbeiter.",
    descriptionEn: "Worked as Service Desk staff.",
    details: "Täglicher Umgang mit Kunden und vielen verschiedenen IT-Systemen. Dabei habe ich gelernt, Probleme schnell zu verstehen und sie gezielt zu lösen.",
    detailsEn: "Daily interaction with customers and various IT systems. I learned to quickly understand problems and solve them effectively."
  },
  {
    id: "5",
    role: "Junior ICT System Admin",
    roleEn: "Junior ICT System Admin",
    company: "Liechtensteinische Landesverwaltung",
    companyEn: "Liechtenstein National Administration",
    period: "2023 - Heute",
    periodEn: "2023 - Present",
    description: "Administration und Support der ICT-Systemlandschaft.",
    descriptionEn: "Administration and support of ICT systems.",
    details: "Als Junior ICT System Administrator trage ich die Verantwortung für rund 3.500 mobile Geräte. Ich sorge dafür, dass die MDM-Systeme reibungslos laufen und der digitale Unterricht an den Schulen funktioniert.",
    detailsEn: "As a Junior ICT System Administrator, I am responsible for around 3,500 mobile devices. I ensure that MDM systems run smoothly and that digital learning works at schools."
  },
  {
    id: "6",
    role: "BSc Digital Design",
    roleEn: "BSc Digital Design",
    company: "Ostschweizer Fachhochschule",
    companyEn: "Eastern Switzerland University of Applied Sciences",
    period: "2024 - Heute",
    periodEn: "2024 - Present",
    description: "Studium mit Fokus auf digitales Design.",
    descriptionEn: "Studies with focus on digital design.",
    details: "Vertiefung in UX/UI Design, Interaction Design und visuelle Kommunikation. Kombination von technischem Wissen und kreativer Gestaltung.",
    detailsEn: "Specialized in UX/UI Design, Interaction Design and Visual Communication. Combination of technical knowledge and creative design."
  }
];
